'TGUI':
  - changed-files:
      - any-glob-to-any-file: ['tgui/**']

'Звук':
  - changed-files:
      - any-glob-to-any-file: ['**/*.ogg']

'Изменение Карты':
  - all:
      - changed-files:
          - any-glob-to-any-file: ['**/*.dmm']
          - all-globs-to-all-files: ['!_maps/map_files220/stations/*.dmm']

'Кибериада':
  - changed-files:
      - any-glob-to-any-file: ['_maps/map_files220/stations/boxstation.dmm']

'Керберос':
  - changed-files:
      - any-glob-to-any-file: ['_maps/map_files220/stations/deltastation.dmm']

'Цереброн':
  - changed-files:
      - any-glob-to-any-file: ['_maps/map_files220/stations/metastation.dmm']

'Фаррагус':
  - changed-files:
      - any-glob-to-any-file: ['_maps/map_files220/stations/cerestation.dmm']

'Спрайты':
  - changed-files:
      - any-glob-to-any-file: ['**/*.dmi']

'Инструменты':
  - changed-files:
      - any-glob-to-any-file: ['.gihub/workflows/**', 'tools/**']

'Требуется изменение конфига':
  - changed-files:
      - any-glob-to-any-file: ['config/**']

'Документация':
  - changed-files:
      - any-glob-to-any-file: ['**/*.md']

'SQL':
  - changed-files:
      - any-glob-to-any-file: ['SQL/**']

'Частичная модульность':
  - all:
      - changed-files:
          - any-glob-to-any-file: ['code/**']
          - any-glob-to-any-file: [modular_ss220/**]
      - base-branch: 'master'

'НЕ МОДУЛЬНО':
  - all:
      - changed-files:
          - any-glob-to-any-file: ['code/**', 'icons/**', '_maps/map_files/**']
          - all-globs-to-all-files: '!modular_ss220/**'
      - base-branch: 'master'

':pencil: Перевод':
  - base-branch: 'translate'

'Фикс':
  - head-branch: ['^fix', 'fix']

':trollface: Фича':
  - head-branch: ['^feat', 'feat']
